// Generated by CoffeeScript 1.6.3
(function() {
  window.CS = function() {
    var createBoard, getNeighbors, nextStep, shouldLive;
    createBoard = function() {
      return [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]];
    };
    getNeighbors = function(board, x, y) {
      var modX, modY, sum, _i, _j, _ref, _ref1;
      sum = 0;
      for (modX = _i = -1; _i <= 1; modX = ++_i) {
        for (modY = _j = -1; _j <= 1; modY = ++_j) {
          if ((0 <= (_ref = x + modX) && _ref < 10) && (0 <= (_ref1 = y + modY) && _ref1 < 10) && x !== 0 || y !== 0) {
            sum += board[x + modX][y + modY];
          }
        }
      }
      return sum;
    };
    shouldLive = function(board, x, y) {
      var neighbors;
      neighbors = getNeighbors(board, x, y);
      return neighbors === 3 || (neighbors === 2 && board[x][y]);
    };
    nextStep = function(board) {
      var cell, nextBoard, row, x, y, _i, _j, _len, _len1;
      nextBoard = createBoard();
      for (x = _i = 0, _len = board.length; _i < _len; x = ++_i) {
        row = board[x];
        for (y = _j = 0, _len1 = row.length; _j < _len1; y = ++_j) {
          cell = row[y];
          nextBoard[x][y] = shouldLive(board, x, y) ? 1 : 0;
        }
      }
      return nextBoard;
    };
    return {
      createBoard: createBoard,
      getNeighbors: getNeighbors,
      shouldLive: shouldLive,
      nextStep: nextStep
    };
  };

}).call(this);
